def magenta_grid_sheet(rows, cols, cell: int = 100, drift=None): ...
def cyan_squares(n, side: int = 10, bg=(0, 0, 0)): ...
def clean_image(): ...
def filled_mask(size, box): ...
def alpha_blob(size, box): ...
