from PIL import Image as Image
from _typeshed import Incomplete

CELL_PX: Incomplete
PAD: Incomplete
FIXTURES: Incomplete

def test_arm_a_paints_every_ordered_face_and_never_a_flat_mat_colors_fill() -> None: ...
def test_arm_a_paints_every_view_not_just_one() -> None: ...
def test_arm_a_leaves_no_unpainted_pixel_inside_any_face_mask_region() -> None: ...
def test_arm_a_leaves_no_unpainted_pixel_across_multiple_views() -> None: ...
