TEXTURES_JSON: str

def test_load_textures_parses_the_real_textures_json_with_known_families() -> None: ...
def test_face_texture_wall_band_top_uses_wall_mat_top_family() -> None: ...
def test_face_texture_blank_and_thatch_mat_default_to_stone() -> None: ...
def test_face_texture_base_top_is_always_floor_stone_regardless_of_mat() -> None: ...
def test_face_texture_any_side_face_uses_wall_mat_side_family() -> None: ...
def test_face_texture_roof_slope_is_roof_shingle() -> None: ...
def test_face_texture_gable_kind_still_maps_to_roof_shingle() -> None: ...
def test_face_texture_stair_top_is_stair_tread_and_bottom_is_floor_stone() -> None: ...
def test_face_texture_stair_sides_are_all_riser_after_r2_4_cover_only() -> None: ...
def test_face_texture_never_raises_for_an_unmapped_module() -> None: ...
def test_face_texture_id_type_and_dims_agree_with_textures_json() -> None: ...
def test_variant_depends_only_on_world_column_not_z_view_invariance() -> None: ...
def test_variant_shows_at_least_two_distinct_ids_across_many_world_columns() -> None: ...
def test_variant_id_is_a_real_textures_json_key_in_its_own_family() -> None: ...
