from _typeshed import Incomplete

ROOT: Incomplete
GOLDEN: Incomplete
CELL_PX: int
GOLDEN_SPECS: Incomplete

def test_content_extent_oblique_matches_bbox_extent() -> None: ...
def test_content_extent_top_zero_dim_uses_min_thick() -> None: ...
def test_content_extent_cardinal_ns_folds_top() -> None: ...
def test_panel_fit_scale_matches_legacy_fit_scale() -> None: ...
def test_draw_iso_panel_accepts_forced_scale_and_returns_bbox() -> None: ...
def test_render_cells_shared_scale_uniform_px_per_voxel() -> None: ...
def test_legacy_autofit_flag_reproduces_golden_bytes(tmp_path) -> None: ...
def test_write_scale_sidecar_creates_expected_keys(tmp_path) -> None: ...
def test_write_scale_sidecar_extends_existing_file(tmp_path) -> None: ...
def test_make_tile_guide_generate_writes_sidecar(tmp_path) -> None: ...
def test_cross_view_dims_clean_on_shared_scale() -> None: ...
def test_cross_view_dims_flags_legacy_mismatch() -> None: ...
def test_sheet_qc_cli_exit_codes(tmp_path) -> None: ...
def test_specs_md_has_corrective_factor_appendix() -> None: ...
