def test_four_turns_is_the_identity_on_grid_groups_and_overlays() -> None: ...
def test_group_shape_survives_every_rotation() -> None: ...
def test_group_ascent_arrow_advances_one_step_clockwise_per_turn() -> None: ...
def test_a_material_overlay_travels_with_its_own_cell() -> None: ...
def test_wall_count_round_trips_through_every_one_of_the_nine_views() -> None: ...
def test_group_cell_count_round_trips_through_every_one_of_the_nine_views() -> None: ...
