CELL_PX: int
PAD: int

def test_sheet_grid_leaves_the_bottom_right_cell_blank() -> None: ...
def test_arm_b_is_blank_technical_with_zero_cyan_residue() -> None: ...
def test_arm_bc_adds_cyan_symbols_over_arm_b() -> None: ...
def test_arm_a_matches_the_sheet_grid_size() -> None: ...
def test_stage_writes_three_arm_sheets_a_manifest_and_the_three_restyle_prompts(tmp_path) -> None: ...
