from _typeshed import Incomplete

CELL_PX: int
PAD: int
GRID_COLS: Incomplete
GRID_ROWS: Incomplete

def test_per_module_sheet_grid_is_five_by_two_with_a_blank_bottom_right_cell() -> None: ...
def test_arm_b_is_blank_technical_with_zero_cyan_residue() -> None: ...
def test_arm_bc_adds_cyan_symbols_over_arm_b() -> None: ...
def test_arm_a_matches_the_sheet_grid_size() -> None: ...
def test_per_module_sheet_has_magenta_gutter_separators() -> None: ...
def test_stage_writes_one_stem_pair_per_module_arm_a_only(tmp_path) -> None: ...
def test_stage_sheet_dims_are_four_x_the_prior_64px_cell(tmp_path) -> None: ...
def test_stage_still_writes_per_module_view_masks_and_one_manifest(tmp_path) -> None: ...
