def test_floor_has_closed_horizontal_borders() -> None: ...
def test_floor_vertical_edges_are_open_for_horizontal_continuity() -> None: ...
def test_floor_variants_share_global_courses() -> None: ...
def test_wall_tiling_edges_are_open_too() -> None: ...
def test_single_door_hinges_left_knob_right() -> None: ...
def test_build_set_renders_everything(tmp_path) -> None: ...
