from _typeshed import Incomplete

CABIN: str
GOLDEN: Incomplete
GOLDEN_VIEWS: Incomplete

def cabin(): ...
def kit_root(tmp_path_factory): ...
def test_the_cabin_fixture_carries_everything_a_style_verdict_needs(cabin) -> None: ...
def test_every_view_renders_sprites_and_a_manifest_through_the_seam(cabin, kit_root) -> None: ...
def test_every_manifest_tile_resolves_to_a_sprite_this_kit_carries(cabin, kit_root) -> None: ...
def test_geometry_round_trips_through_all_nine_views(cabin) -> None: ...
def test_both_wall_materials_survive_every_rotation(cabin) -> None: ...
def test_assembled_view_is_deterministic_and_not_blank(cabin, kit_root) -> None: ...
def test_manifest_matches_golden(cabin, kit_root, view) -> None: ...
