def test_table_covers_the_nine_facings_as_four_dimetric_four_cardinal_and_top() -> None: ...
def test_every_family_uses_each_of_the_four_grid_turns_exactly_once() -> None: ...
def test_dimetric_projection_is_byte_identical_to_the_legacy_scene_camera() -> None: ...
def test_a_unit_ground_cell_projects_to_the_same_screen_area_in_every_view() -> None: ...
def test_cardinal_sees_walls_face_on_and_dimetric_does_not() -> None: ...
def test_cull_axis_is_the_camera_depth_direction_plus_up() -> None: ...
def test_height_reads_upward_in_every_view_except_top() -> None: ...
