import pytest
from _typeshed import Incomplete

ROOT: Incomplete
LAYOUT: Incomplete
KIT_DIR: Incomplete

def layout(): ...
@pytest.fixture
def metadata_only_kit_dir(tmp_path): ...
def test_load_kit_meta_reads_json_without_pngs(metadata_only_kit_dir) -> None: ...
def test_build_manifest_succeeds_against_metadata_only_kit(layout, metadata_only_kit_dir) -> None: ...
