CELL_PX: int
PAD: int

def test_yaws_and_views_are_the_documented_nine() -> None: ...
def test_render_module_yields_all_nine_views_as_rgba() -> None: ...
def test_render_module_is_deterministic() -> None: ...
def test_silhouette_bbox_differs_across_at_least_four_of_eight_yaws() -> None: ...
def test_ordered_faces_ids_are_stable_and_uniquely_formatted_per_panel() -> None: ...
def test_shared_scale_is_one_value_that_fits_every_panel_of_every_module() -> None: ...
def test_build_sheet_manifest_records_scale_once_at_sheet_level_not_per_panel() -> None: ...
def test_face_mask_regions_are_single_valued_and_within_the_render_silhouette(): ...
def test_face_mask_meta_records_bbox_and_positive_pixel_count_per_face() -> None: ...
def test_save_mask_writes_the_documented_png_and_json_pair(tmp_path) -> None: ...
def test_ordered_faces_and_ordered_enclosure_faces_partition_stair_45_with_no_overlap() -> None: ...
def test_ordered_enclosure_faces_are_tagged_stair_enclosure_for_stairs() -> None: ...
def test_enclosure_faces_reuses_render_modules_per_view_origin_for_pixel_alignment() -> None: ...
