from _typeshed import Incomplete

FIXTURES: Incomplete

def test_flat_roof_spans_one_level() -> None: ...
def test_shed1_stair_spans_rise_with_position() -> None: ...
def test_box_has_z0_single_level_wall() -> None: ...
def test_groups_fixture_emits_one_grp_box_per_group_cell_matching_voxel_span() -> None: ...
