from _typeshed import Incomplete

UNIT_SQUARE: Incomplete
EXPECTED_MODULES: Incomplete

def test_extrude_unit_square_emits_top_bottom_and_four_sides() -> None: ...
def test_extrude_faces_are_valid_polygons() -> None: ...
def test_extrude_mat_is_tagged_on_every_face() -> None: ...
def test_from_boxes_wraps_a_layout_massing_box() -> None: ...
def test_from_boxes_concatenates_multiple_boxes_without_sharing_faces() -> None: ...
def test_modules_has_exactly_the_nine_named_builders() -> None: ...
def test_every_builder_returns_nonempty_deterministic_face_list() -> None: ...
def test_top_cap_and_base_are_thinner_than_wall_band(): ...
def test_door_and_window_are_standalone_thin_slabs() -> None: ...
def test_door_1x2_and_window_1x1_are_geometrically_distinct() -> None: ...
def test_slab_thickness_matches_the_shared_slab_thick_constant() -> None: ...
def test_diag_half_is_a_thin_rotated_quad_extrusion() -> None: ...
def test_roof_cell_renders_only_the_two_slopes_gable_and_bottom_are_mask_only() -> None: ...
def test_stair_45_and_stair_half_are_one_zigzag_solid_tread_riser_render_only() -> None: ...
def test_stair_half_rises_to_half_the_height_of_stair_45(): ...
