def test_stage_writes_enclosure_masks_per_view_for_stairs_and_roof_with_nonzero_coverage(tmp_path) -> None: ...
def test_stage_writes_no_enclosure_masks_for_a_module_with_no_enclosure_faces(tmp_path) -> None: ...
