def test_door_front_and_back_use_the_pinned_decal_id() -> None: ...
def test_window_front_and_back_use_the_pinned_decal_id() -> None: ...
def test_door_thin_edges_and_caps_are_plain_wood_not_the_decal() -> None: ...
def test_flip_h_is_true_only_on_a_slabs_back_face() -> None: ...
def test_flip_h_is_false_for_every_non_slab_face() -> None: ...
