from _typeshed import Incomplete

CELL_PX: Incomplete
PAD: Incomplete
S: Incomplete

def test_closed_box_strokes_every_edge_of_every_face() -> None: ...
def test_open_cover_strokes_the_shared_ridge_plus_the_unmatched_silhouette() -> None: ...
def test_a_shared_edge_between_same_normal_faces_is_not_stroked() -> None: ...
def test_edge_width_is_about_2px_at_512_and_scales_down_with_cell() -> None: ...
def test_paint_panel_draws_dark_ink_at_a_known_different_normal_boundary() -> None: ...
