from _typeshed import Incomplete

UNIT_SQUARE: Incomplete
EXPECTED_MODULES: Incomplete

def test_extrude_unit_square_emits_top_bottom_and_four_sides() -> None: ...
def test_extrude_faces_are_valid_polygons() -> None: ...
def test_extrude_mat_is_tagged_on_every_face() -> None: ...
def test_from_boxes_wraps_a_layout_massing_box() -> None: ...
def test_from_boxes_concatenates_multiple_boxes_without_sharing_faces() -> None: ...
def test_modules_has_exactly_the_nine_named_builders() -> None: ...
def test_every_builder_returns_nonempty_deterministic_face_list() -> None: ...
def test_top_cap_and_base_are_thinner_than_wall_band(): ...
def test_recess_builders_split_the_opening_side_into_more_faces_than_plain_wall() -> None: ...
def test_recess_door_and_recess_window_are_geometrically_distinct() -> None: ...
def test_diag_half_is_a_thin_rotated_quad_extrusion() -> None: ...
def test_roof_cell_is_a_triangular_prism_wedge() -> None: ...
def test_stair_45_and_stair_half_are_built_from_steps_worth_of_boxes() -> None: ...
def test_stair_half_rises_to_half_the_height_of_stair_45(): ...
