from _typeshed import Incomplete

ROOT: Incomplete
LAYOUT: Incomplete
KIT_DIR: Incomplete

def layout(): ...
def manifest(layout): ...
def test_tiles_have_all_fields(manifest) -> None: ...
def test_walls_are_walldefs(manifest) -> None: ...
def test_run_export_cli_verb(tmp_path) -> None: ...
def test_validate_clean_manifest_passes(manifest) -> None: ...
def test_validate_catches_out_of_range_ax(manifest) -> None: ...
def test_wall_count_matches_dsl(manifest, layout) -> None: ...
def test_door_window_stair_tile_counts(manifest) -> None: ...
def test_tile_assets_resolve_in_kit(manifest) -> None: ...
def test_validate_manifest_flags_missing_asset(manifest) -> None: ...
