def test_detect_grid_matches_even_division_no_drift() -> None: ...
def test_strip_linework_removes_magenta_keeps_blob_body() -> None: ...
def test_strip_linework_keeps_interior_near_white_pixel() -> None: ...
