from _typeshed import Incomplete

FIXTURES: Incomplete

def test_valid_v2_fixture_parses_clean(fixture) -> None: ...
def test_misplaced_marker_is_an_error() -> None: ...
def test_bad_stair_incl_is_an_error() -> None: ...
def test_double_booked_voxel_is_an_error() -> None: ...
