from _typeshed import Incomplete

CELL_PX: Incomplete
PAD: Incomplete
ORIGIN: Incomplete
S: Incomplete

def test_face_axes_south_and_north_walls_have_opposite_chirality() -> None: ...
def test_warp_tiling_solid_png_fills_screen_poly_interior_and_leaves_outside_transparent() -> None: ...
def test_warp_tiling_wall_face_tiles_vertically_three_times_and_rep_count_is_scale_invariant(): ...
def test_warp_tiling_handles_a_three_corner_gable_face_via_affine() -> None: ...
def test_warp_tiling_marks_the_same_physical_corner_across_two_different_yaws() -> None: ...
def test_warp_decal_places_exactly_one_copy_mask_tight_no_tiling() -> None: ...
