from _typeshed import Incomplete
from pathlib import Path

TARGET_SIZES: Incomplete
VALID_TYPES: Incomplete
FOLDER_NAMES: Incomplete

def remove_background(input_path: Path) -> Image.Image: ...
def resize_with_padding(img: Image.Image, target_size: tuple[int, int]) -> Image.Image: ...
def find_content_root(start: Path) -> Path: ...
def main() -> None: ...
