import numpy as np
import trimesh

def rotate_y(mesh: trimesh.Trimesh, degrees: float) -> trimesh.Trimesh: ...
def rotate_axis(mesh: trimesh.Trimesh, degrees: float, axis: np.ndarray) -> trimesh.Trimesh: ...
def main() -> None: ...
