from _typeshed import Incomplete

def parse_args(): ...

AZIMUTHS: Incomplete
ORTHO_SCALES: Incomplete
CENTER_Z_VALS: Incomplete
ELEVATION: float
RESOLUTION_X: Incomplete
RESOLUTION_Y: Incomplete

class _FBXStub:
    axis_forward: str
    axis_up: str
    def report(self, level, msg) -> None: ...

def import_fbx(fbx_path): ...
def apply_solid_material(mesh_objs) -> None: ...
def setup_scene(): ...
def make_camera(scene, ortho_scale, center_z, azimuth_deg, elevation_deg): ...
def main() -> None: ...
