def mesh_z_range(mesh_objs) -> tuple[float, float]: ...
def mesh_x_range(mesh_objs) -> tuple[float, float]: ...
def apply_character_materials(mesh_objs, z_min: float, z_max: float) -> None: ...
def apply_uv_texture(mesh_objs, front_path: str, back_path: str, x_min: float, x_max: float, z_min: float, z_max: float) -> None: ...
def apply_solid_material(mesh_objs) -> None: ...
