from _typeshed import Incomplete

LATERAL_TAGS: Incomplete

def lateral_faces(module, view, s, cell_px, pad, origin): ...
def save_enclosure_masks(module, view, ordered, s, cell_px, pad, origin, masks_path): ...
