from _typeshed import Incomplete

DIMETRIC: Incomplete

def panel_family(view, family=...): ...
def yaw_deg(view): ...
def panel_cam(view, s, cell_px, pad, origin, family=...): ...
def ordered_front_faces(faces, view, cam): ...
def ordered_faces(faces, view, cam): ...
def ordered_enclosure_faces(faces, view, cam): ...
def project_face(pts, view, s, cell_px, pad, origin, family=...): ...
