from _typeshed import Incomplete
from dataclasses import dataclass, field

CYAN: Incomplete
BG_MAX: int

@dataclass
class MarkParams:
    scheme: str = ...
    back_mode: str = ...
    opacity: float = ...
    n_cols: int = ...
    radius_frac: float = ...
    stroke: int = ...
    back_views: set = field(default_factory=Incomplete)
    skip_views: set = field(default_factory=Incomplete)

SYMBOLS: Incomplete

def apply_marks(img, panels, params=None): ...
def residue_count(img, tol: int = 60): ...
def tile_panels(img, layout_name): ...
def main() -> None: ...
