from _typeshed import Incomplete
from face_project import ordered_front_faces as ordered_front_faces, project_face as project_face

YAWS: Incomplete
VIEWS: Incomplete

def panel_extent(faces, view, s: float = 1.0, family=...): ...
def shared_scale(module_names, cell_px, pad, families=...): ...
def render_panel(faces, view, s, cell_px, pad, family=...): ...
def render_module(name, s, cell_px, pad, family=...): ...
def enclosure_faces(name, s, cell_px, pad, origins, family=...): ...
def build_sheet_manifest(panels, s): ...
