from _typeshed import Incomplete

CELL_PX: int
PAD: int
WALL_MATS: Incomplete
YAW_FOR_SIDE: Incomplete

def piece_specs(): ...
def shared_px_per_voxel(cell_px=..., pad=...): ...
def render_piece(module, view, mat, s, family=..., cell_px=..., pad=...): ...
def build_kit(out_dir, family=..., cell_px=..., pad=..., s=None): ...
def build_all(out_root, cell_px=..., pad=...): ...
