from dataclasses import dataclass

@dataclass
class Face:
    pts: list
    kind: str
    mat: str = ...
    enclosure: str = ...

def extrude(footprint, z0, h, mat: str = 'blank'): ...
def from_boxes(boxes, mat: str = 'blank'): ...
