from _typeshed import Incomplete

YAWS: Incomplete
VIEWS: Incomplete

def ordered_faces(faces, view, cam): ...
def panel_extent(faces, view, s: float = 1.0): ...
def shared_scale(module_names, cell_px, pad): ...
def render_panel(faces, view, s, cell_px, pad): ...
def render_module(name, s, cell_px, pad): ...
def project_face(pts, view, s, cell_px, pad, origin): ...
def build_sheet_manifest(panels, s): ...
