def candidates(piece, mat: str = '', direction: str = ''): ...
def resolve(kit_pieces, piece, mat: str = '', direction: str = ''): ...
def asset_name(kit_pieces, piece, mat: str = '', direction: str = ''): ...
