def rotate_arrow(ch, turns: int = 1): ...
def rotate_grid_cw(grid, turns: int = 1): ...
def rotate_cells(cells, rows, cols, turns: int = 1): ...
def rotate_attrs(attrs, rows, cols, turns: int = 1): ...
