from _typeshed import Incomplete

TREAD_H: Incomplete
RISER_H: Incomplete

def floor_wood(seed): ...
def roof_shingle(seed): ...
def stair_tread(seed): ...
def stair_riser(seed): ...
def grass(seed): ...
def road_cobble(seed): ...
def road_dirt(seed): ...

EXTRA: Incomplete
