from _typeshed import Incomplete

T: int
INK: str
STROKE: float
EDGE_MARGIN: int
FLOOR_COURSES: Incomplete
WALL_STONE_COURSES: Incomplete
PLANK_STEP: int

def floor_stone(seed): ...
def wall_wood_side(seed): ...
def wall_wood_top(seed): ...
def wall_stone_side(seed): ...
def wall_stone_top(seed): ...
def window_1x1(): ...

SET: Incomplete

def build_set(out_dir: str = 'assets/textures'): ...
