from _typeshed import Incomplete

def kit_dir_for(kit_root, view): ...

ARMS: Incomplete

def render_scene(layout, view, kit_root, arm: str = 'a'): ...
def render_image(layout, view, kit_root): ...
def bake(layout, kit_root, out_dir, views=None, arm: str = 'a'): ...
def build_kits(kit_root): ...
