from layout_massing import massing as massing
from layout_parse import rotate_cw as rotate_cw
from scene_guide_render import Cam as Cam, VIEW_TURNS as VIEW_TURNS

MARGIN: int

def piece_of(box): ...
def load_kit_meta(kit_dir): ...
def load_kit(kit_dir): ...
def paint_key(family, box): ...
def assemble(layout, view, kit_dir): ...
def main() -> None: ...
