from _typeshed import Incomplete

VIEW_TURNS: Incomplete

class _Cam:
    def __init__(self, boxes, avail_w, avail_h, pad) -> None: ...
    def pt(self, u, v, z): ...

def render_scene_panel(layout, view, size, pad: int = 24): ...
def render_plan_panel(layout, size, pad: int = 24): ...
