from _typeshed import Incomplete
from math import ceil as ceil

CELL_PX: int
PAD: int
GRID_COLS: Incomplete
GRID_ROWS: Incomplete
GUTTER: int
MAGENTA: Incomplete
MAT_COLORS: Incomplete

def sheet_grid(panels): ...
def arm_b(panels): ...
def arm_bc(panels): ...
def paint_panel(module, view, ordered, s, cell_px, pad, origin): ...
def arm_a(panels, ordered_by_panel): ...
def stage(out: str = 'output/gen-inbox', out_masks=None) -> None: ...
