from _typeshed import Incomplete

CELL_PX: int
PAD: int
MAT_COLORS: Incomplete

def sheet_grid(panels): ...
def arm_b(panels): ...
def arm_bc(panels): ...
def arm_a(panels, ordered_by_panel): ...
def stage(out: str = 'output/gen-inbox', out_masks=None) -> None: ...
