from _typeshed import Incomplete

RESAMPLE: Incomplete
SUPERSAMPLE: int

def tile_source(tex_img, canvas_w, canvas_h): ...
def match_source_density(source_img, texcoords, dst_poly): ...
def supersample_transform(source_img, method, size, coeffs_fn, dst_poly, src_pts): ...
