from _typeshed import Incomplete

FAMILIES: Incomplete
VIEW_TABLE: Incomplete
VIEWS: Incomplete
VIEW_TURNS: Incomplete
DIMETRIC: str

def family(view): ...
def turns(view): ...
def matrix(family_name): ...
def cull_axis(family_name): ...
def project(family_name, u, v, z): ...
def depth_key(family_name, u, v, z): ...
