from _typeshed import Incomplete

WORKFLOW_DIR: Incomplete

def gen_character(prompt: str, profile_name: str, output_path: str | None) -> None: ...
def style_concept(input_image: str, prompt: str, denoise: float, output_path: str | None) -> None: ...
def ipadapter_ref(input_image: str, prompt: str, weight: float, output_path: str | None) -> None: ...
