import argparse
from PIL import Image as Image
from pathlib import Path

def parse_watermark_region(text: str | None) -> tuple[float, float, float, float] | None: ...
def parse_args() -> argparse.Namespace: ...
def run(args: argparse.Namespace) -> list[Path]: ...
def main() -> None: ...
