from PIL import Image

RB_MIN: int
G_MAX: int
WHITE_MIN: int
EDGE_BAND: int
LINE_STRENGTH_MIN: int
SEARCH_FRAC: float

def magenta_mask(img: Image.Image) -> Image.Image: ...
def white_mask(img: Image.Image) -> Image.Image: ...
def line_mask(img: Image.Image) -> Image.Image: ...
def detect_boundaries(mask: Image.Image, count: int, axis: int) -> list[int]: ...
def detect_grid(img: Image.Image, rows: int, cols: int) -> tuple[list[int], list[int]]: ...
def strip_linework(img: Image.Image, band: int = ...) -> Image.Image: ...
