from PIL import Image as Image

ALPHA_MIN: int
LUMA_MIN: int

def silhouette_mask(img: Image.Image, alpha_min: int = ...) -> Image.Image: ...
def mask_iou(a: Image.Image, b: Image.Image) -> float: ...
def silhouette_iou(cell: Image.Image, box_mask: Image.Image, alpha_min: int = ...) -> float: ...

DIM_TOLERANCE: float

def cross_view_dims(scale_info: dict, tol: float = ...) -> list: ...
