from PIL import Image
from _typeshed import Incomplete
from pathlib import Path

DEFAULT_LAYOUTS: dict[str, list[list[str]]]

class SheetLayout:
    name: Incomplete
    grid: Incomplete
    def __init__(self, name: str, grid: list[list[str]]) -> None: ...
    @classmethod
    def get(cls, name: str) -> SheetLayout: ...
    @property
    def rows(self) -> int: ...
    @property
    def cols(self) -> int: ...
    def labels(self) -> list[str]: ...
    def non_caption_labels(self) -> list[str]: ...
    def expected_cells(self) -> int: ...

def load_image(path: Path) -> Image.Image: ...
def split_cells(img: Image.Image, xs: list[int], ys: list[int], *, padding: int = 0) -> list[Image.Image]: ...
def even_boundaries(size: int, count: int) -> list[int]: ...
def split_grid(img: Image.Image, rows: int, cols: int, *, padding: int = 0) -> list[Image.Image]: ...
def remove_background(img: Image.Image) -> Image.Image: ...
def remove_watermark(img: Image.Image, *, region: tuple[int, int, int, int] | None = None) -> Image.Image: ...
