import argparse
from _typeshed import Incomplete
from pathlib import Path

CANONICAL_DIRS: Incomplete

def parse_args() -> argparse.Namespace: ...
def split_sheet(sheet_path: Path, rows: int, cols: int, padding: int = 0): ...
def remove_bg(img): ...
def next_index(out_root: Path, prefix: str, direction: str) -> int: ...
def main() -> None: ...
