from _typeshed import Incomplete

COMFY_BASE_URL: Incomplete
PROMPT_URL: Incomplete
UPLOAD_URL: Incomplete
TIMEOUT_SECONDS: int

def get_comfy_dir() -> str: ...
def get_output_dir() -> str: ...
def upload_image(image_path: str) -> str: ...
def send_prompt(workflow: dict) -> dict | None: ...
def snapshot_pngs() -> set[str]: ...
def wait_for_new_png(before: set[str]) -> str | None: ...
def load_workflow(path: str) -> dict: ...
def copy_to_dir(src: str, dst_dir: str) -> str: ...
