from _typeshed import Incomplete

COMFY_URL: str
BASE_DIR: Incomplete
CONTENT_DIR: Incomplete
PROFILE_DIR: Incomplete
WORKFLOW_DIR: Incomplete

def get_comfy_dir(): ...
def get_output_dir(): ...
def copy_to_destination(src, dst) -> None: ...
def get_latest_image(output_dir=None): ...
def apply_output_path(workflow, output_path) -> None: ...
def load_profile(profile_name): ...
def load_workflow(prompt_text, profile_name): ...
def send_prompt(workflow): ...
def gen_character(prompt, profile_name, output_path) -> None: ...
def main() -> None: ...
