from _typeshed import Incomplete

BASE_DIR: Incomplete
CONTENT_DIR: Incomplete
PROFILE_DIR: Incomplete
WORKFLOW_DIR: Incomplete
HELP: str

def apply_random_seeds(workflow: dict) -> None: ...
def inject_prompt(workflow: dict, prompt_text: str) -> None: ...
def inject_input_image(workflow: dict, comfy_filename: str) -> None: ...
def set_base_denoise(workflow: dict, denoise: float) -> None: ...
def gen_character(prompt: str, profile_name: str, output_path: str | None) -> None: ...
def style_concept(input_image: str, prompt: str, denoise: float, output_path: str | None) -> None: ...
def get_arg(args: list[str], flag: str, default: str | None = None) -> str | None: ...
def main() -> None: ...
