def apply_random_seeds(workflow: dict) -> None: ...
def inject_prompt(workflow: dict, prompt_text: str) -> None: ...
def inject_input_image(workflow: dict, comfy_filename: str) -> None: ...
def inject_concept_image(workflow: dict, comfy_filename: str) -> None: ...
def set_base_denoise(workflow: dict, denoise: float) -> None: ...
def set_ipadapter_weight(workflow: dict, weight: float) -> None: ...
def inject_output_size(workflow: dict, width: int, height: int) -> None: ...
